# -*- coding: utf-8 -*-
"""lol

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oHAf7_Iti24jgLAt-MP4RTOxW7pXM41
"""

print("ur a first-year in scripps's afjrotc program.. or sum shit... u look around the grinder and decide to explore.")
name = input("but first, what's your name? ")
print("alrighty then,", name)

print("""
wut u explore first gang
[1]. the weird guy wearing a neon orange shirt typing intensely in the middle room
[2]. a person with a large milk tea boba staring judgementally at passerbys
[3]. the vollyballers rallying with the net
[4]. the short guy with a rifle
""")
choose = input("")
if choose == "1" :
   print("You chose to approach the weird guy!")
   print("you slowly walk towards the guy with the offensively bright shirt and your footsteps go undetected by him.")
   print("that is what you believe until you get a little closer and he shoots out of his chair, staring directly at you, and he looks a little ... mad")
   toveer = input("what do you say to him? ")
   if toveer == "Hi Veer" :
    print("his face melts, and suddenly he looks like a normal person and he smiles at you.")
    print("'you must be a first-year! welcome! i can't believe you knew my name! you must be " + name + "!!!'")
    print("GOOD SECRET ENDING!!!")
   if toveer != "Hi Veer" :
      print("before you can say anything, the traffic cone man rears up his head and swallows you whole like a python...")
      print("YOU DIED. BAD ENDING 1")

if choose == "2" :
   print("You chose to approach the judgmental boba person!")
   print("the boba person was leaning against the doorframe of the logistics room, already eyeing you down by the time you take a few steps. they don't offer any greeting")

   print("""
   what do you do?
   [1]. offer a smile
   [2]. stare judgmentally back
   """)
   choose = input("")
   if choose == "1" :
    print("they narrow their eyes even more, gripping their drink so hard that the bottom of the dayung cup bursts. as the tea soaks into their jeans, they don't tear their furious eyes off you")
    print("in a flash, they're on top of you, digging their nails into your eyes until they reach your brain. nobody moves to stop them")

    print("YOU DIED. BAD ENDING 2")
   if choose == "2" :
    print("you stare judgmentally back. apparently, the person isn't used to being given the same energy, because they storm up to you immediately")
    print("'you better quit with that attitude" + ",", name + "'")
    print("'im an officer and i can and WILL demerit you'")

    print("""
    what do you respond with?
    [1]. idgaf!!!
    [2]. im sowwy
    """)
    choose = input("")
    if choose == "1" :
      print("that's it. you have done it now. they grab you by the ear, smashing your head into a nearby table over and over until your brains resemble something of the boba they drink")

      print("YOU DIED. BAD ENDING 3")
    if choose == "2" :
      print("they roll their eyes, mumbling something about how they'll get you next time, but it looks like you're in the clear! for now...")

      print("THE GOOD ENDING! I wonder if there's a second one...")

if choose == "3" :
   print("You approach the volleyballers!")
   print("There's a group of people playing volleyball, seeming very absorbed in their game. you decide to take a closer look to enjoy the game")
   print("'WATCH OUT!")
   print("""
   quick! decide!
   [1]. scream
   [2]. duck
   """)
   choose = input("")
   if choose == "1" :
    print("you scream loudly, but that doesn't stop the ball from flying straight into your head with screams of " + "'" + name + "!!'" )
    print("as the ball collides with your head, you pass out and are rushed to the hosptial. you suffer a concussion, but are alive")

    print("you are alive... until a familiar face comes to see you in your room. one of the volleyballers")
    print("unable to speak or move, you watch in horror as the boy with the nametag 'godinez' unplugs your fluids and oxygen")

    print("YOU DIED. BAD ENDING 4")
   if choose == "2" :
    print("you duck from whatever might be heading towards you, but the ball ends up slamming into your face anyway")
    print("your brain shakes in your skull, and the impact causes you to pass on the spot")

    print("YOU DIED. BAD ENDING 5")
if choose == "4" :
   print("You approach the short guy!")
   print("he seems to be very focused on what he's doing, spinning and banging the rifle on the ground in all sorts of ways. you're intrigued and decide to strike up a conversation")
   print("""
   [1]. you're kind of short
   [2]. what are you doing
   [3]. are you a sophomore
   """)
   choose = input("")
   if choose == "1" :
    print("you tell him how it is; he's short. he just kind of stares at you and doesn't respond. you wait for a while,")
    print("but he still doesn't respond")
    print("you feel like you should say more")
    print("""
    [1]. hi, i'm a freshman
    [2]. you look funny
    """)
    if choose == "1" :
      print("your introduction is not taken well. holy shit. he has laser eyes.")
      print("the moment you say that, his face contorts in rage, and he obliterates you with his laser eyeballs")
      print("YOU DIED. BAD ENDING 6")
    if choose == "2" :
      print("another comment on his appearance doesn't do you any favors. in fact, you retract in fear as he slowly approaches you, rifle in hand")
      print("'you think you're so funny'")
      print("without a moment to react, he's bashing your head in with the rifle, again and again, and though you said he was short and looked funny, his strength only brought you agony")
      print("YOU DIED. BAD ENDING 7")
   if choose == "2" :
    print("'i'm on armed team. this is what we do. you must be " + name + ".' " + "you narrow your eyes at him, and he ends up taking offense to this. you don't notice")
    print("well, you don't notice until you turn around to move onto peer into the armory, and suddenly the weight of a rifle crashes down on your skull")
    print("YOU DIED. BAD ENDING 8")
   if choose == "3" :
    print("you ask him a simple question, assuming based on his stature and childish appearance")
    print("you don't get an answer before he raises his fist as it detaches from his wrist, a rocket fist flying straight at you")
    print("you explode")
    print("YOU DIED. BAD ENDING 9")

